services:
  rstudio:
    image: 'sibswiss/elixir-sco-spatial-omics:practical_5'
    ports:
      - 8787:8787
    # environment:
    #   - JUPYTER_ENABLE_LAB=yes
    volumes:
      - $PWD:/home/rstudio
    working_dir: /home/rstudio
