import marimo

__generated_with = "0.15.2"
app = marimo.App()


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    # Spatial data integration with scRNA-seq
    ## Day 2 - Practical 3

    #### 23rd January 2025
    #### Ahmed Mahfouz, Benedetta Manzato (LUMC)
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ### Agenda:
    <font size="3">1. Dataset description

    <font size="3">2. Spatial imputation with SpaGE and Tangram

    <font size="3">3. Cell deconvolution with Cell2location

    <font size="3">4. Access image in AnnData object
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    # Dataset: MERFISH spatial transcriptomics dataset of a single adult mouse brain (Zhuang-ABCA-1) (Xiaowei Zhuang)

    <font size="3"> This spatially resolved cell atlas of the whole mouse brain provides a systematic characterization of the spatial organization of transcriptomically defined cell types across the entire adult mouses brain using in situ, single-cell transcriptomic profiling with multiplexed error-robust fluorescence in situ hybridization (MERFISH). A gene panel of 1,122 genes was imaged in 9 million brain cells using **MERFISH**, and spatially resolved, single-cell expression profiling was performed at the whole-transcriptome scale by integrating the MERFISH data with the whole-brain single-cell RNA-sequencing (scRNA-seq) dataset previously generated by the Allen Institute. This resulted in the generation of a comprehensive cell atlas of more than 5,000 transcriptionally distinct cell clusters, belonging to ∼300 major cell types (subclasses), across the whole mouse brain, with high molecular and spatial resolution.
    The authors performed MERFISH imaging on **245 coronal and sagittal sections**, the cell atlas was then spatially registered to the Allen Mouse Brain Common Coordinate Framework (CCFv3), which allows systematic quantifications of the cell composition and organization in individual brain regions as anatomically delineated in the CCFv3. This cell atlas also reveals molecularly-defined brain regions characterized by distinct cell type compositions, spatial gradients featuring gradual changes in the gene-expression profiles of cells, as well as cell-type-specific cell-cell interactions and the molecular basis and functional implications of these cell-cell interactions.

    <font size="3"> The collection spans four mouse specimens (two coronal sets and two sagittal sets):
    - <font size="3">**Zhuang-ABCA-1**: 
      - **Dataset size**: 4.2 million cells spanning 147 coronal sections with a 1,122 gene panel.
      - **Filtered dataset**: 2.8 million cells passed the cell classification confidence score threshold and are displayed in the ABC atlas.

    - <font size="3">**Zhuang-ABCA-2**: 
      - **Dataset size**: 1.9 million cells spanning 66 coronal sections.
      - **Filtered dataset**: 1.2 million cells passed the cell classification confidence score threshold.

    - <font size="3">**Zhuang-ABCA-3**: 
      - **Dataset size**: 2.1 million cells spanning 23 sagittal sections.
      - **Filtered dataset**: 1.6 million cells passed the confidence score threshold.

    - <font size="3">**Zhuang-ABCA-4**: 
      - **Dataset size**: 0.22 million cells spanning 3 sagittal sections.
      - **Filtered dataset**: 0.16 million cells passed the confidence score threshold.


    <font size="3"> We will work with the Brain Coronal 1 collection (Zhuang-ABCA-1); the cell-by-gene matrix of the 8.4 millions cells can be downloaded from the AWS bucket of this animal. The cells are then filtered by cell-classification (label transfer) confidence scores calculated during MERFISH-scRNAseq data integration. 7.0 million cells passed the confidence score threshold for cell subclass label transfer and 5.8 million cells further passed the confidence score threshold for cell cluster label transfer. These 5.8 million cells are included in the cell metadata file that can be downloaded from the the AWS bucket and are displayed on the ABC Atlas. The CCF coordinates of the 5.4 million cells that were registered to the 3D Allen-CCF can be downloaded from the CCF coordinate files in the AWB bucket. The collection spans four mouse specimens (2 coronal sets and 2 sagittal sets). Cells are mapped to the whole mouse brain taxonomy (WMB-taxonomy) and Allen Common Coordinate Framework (Allen-CCF-2020). 
    Refer to Zhang et al, 2023 for more details.


    For more details: [Molecularly defined and spatially resolved cell atlas of the whole mouse brain (Zhang et al. 2023)](https://www.nature.com/articles/s41586-023-06808-9)

    From https://github.com/AllenInstitute/abc_atlas_access/blob/main/notebooks/zhuang_merfish_tutorial.ipynb

    Data Availablity : https://knowledge.brain-map.org/data/5C0201JSVE04WY6DMVC/collections </font>
    """
    )
    return


@app.cell
def _():
    import time

    # Record the start time
    start_time = time.time()
    return start_time, time


@app.cell
def _():
    import warnings

    warnings.filterwarnings("ignore")

    # Importing necessary libraries for spatial data analysis and visualization
    import os, re
    import scanpy as sc
    import scanpy.external as sce
    import seaborn as sns
    import matplotlib.pyplot as plt
    import pandas as pd
    import random
    import numpy as np
    import anndata as ad

    # Display the version of important packages for reproducibility
    sc.logging.print_header()

    # Set the default aesthetics for Scanpy plots
    sc.set_figure_params(
        facecolor="white", figsize=(8, 8)
    )  # White background, figure size 8x8
    sc.settings.verbosity = 0  # Set verbosity to show only errors (0) # errors (0), warnings (1), info (2), hints (3)
    return ad, np, pd, plt, sc, sns


@app.cell
def _():
    data_dir = "day_2/practical_3/data/Zhuang-ABCA-1_Dataset/"
    return (data_dir,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3">We will use the **Zhuang-ABCA-1 dataset**: 4.2 million cell spatial transcriptomics dataset spanning 147 coronal sections with a 1122 gene panel. 2.8 million cells passed cell classification confidence score threshold and displayed in the ABC atlas.

    <font size="3">We decided to work with **one section only**, the one that captures most cells (section 80).

    <img src="img/ABCAtlas_Zhuang-ABCA-1_Coronal Grid.png" width="800" height="300">
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ### Read data 

    <font size="3">We will read the AnnData object that has been filtered to have only section 80 and QC was performed from the authors of the study.
    """
    )
    return


@app.cell
def _(ad, data_dir):
    full_adata = ad.read_h5ad(
        f"{data_dir}/expression_matrices/Zhuang-ABCA-1/20230830/Zhuang-ABCA-1-raw.h5ad"
    )
    return (full_adata,)


@app.cell
def _(full_adata):
    full_adata.obs["brain_section_label"].cat.categories
    return


@app.cell
def _(full_adata):
    # Filter the AnnData object
    adata_section = full_adata[
        full_adata.obs["brain_section_label"] == "Zhuang-ABCA-1.080", :
    ].copy()
    return (adata_section,)


@app.cell
def _(adata_section):
    adata_section
    return


@app.cell
def _():
    # adata_section = ad.read_h5ad(
    #     f"{data_dir}/expression_matrices/Zhuang-ABCA-1/20230830/adata_section80.h5ad"
    # )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3">Spatial coordinates, being metadata about cells/spots are stored either in **`.obs`** or **`.obsm`**

    <font size="3">Spot metadata also contains info about class, subclass, neurotransmitter, patient metadata and section.
    """
    )
    return


@app.cell
def _(adata_section):
    adata_section.obs.head()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> Some spatial tools require the spatial coordinates can be stored as `spatial` or `X_spatial`"""
    )
    return


@app.cell
def _(adata_section, np):
    # Add X_spatial to the right field
    x_spatial = np.array(adata_section.obs[["x", "y"]])

    adata_section.obsm["X_spatial"] = x_spatial
    adata_section.obsm["X_spatial"]
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""<font size="3">Gene information are stored in **`.var`**""")
    return


@app.cell
def _(adata_section):
    adata_section.var.head()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3">Plot the section and color them by all the different classifications avaiable in the metadata (class_color, subclass_color, supertype_color, cluster_color):"""
    )
    return


@app.cell
def _(adata_section, plt, sns):
    # Create the color mapping dictionaries
    class_palette = dict(
        zip(
            adata_section.obs["class"].unique(),
            adata_section.obs["class_color"].unique(),
        )
    )
    subclass_palette = dict(
        zip(
            adata_section.obs["subclass"].unique(),
            adata_section.obs["subclass_color"].unique(),
        )
    )
    supertype_palette = dict(
        zip(
            adata_section.obs["supertype"].unique(),
            adata_section.obs["supertype_color"].unique(),
        )
    )
    cluster_palette = dict(
        zip(
            adata_section.obs["cluster"].unique(),
            adata_section.obs["cluster_color"].unique(),
        )
    )

    # Create the subplots
    fig, axes = plt.subplots(2, 2, figsize=(15, 15))
    fig.suptitle("Scatter Plots of Different Categories", fontsize=16)

    # Plot 'class' using class_color
    sns.scatterplot(
        ax=axes[0, 0],
        x="x",
        y=-adata_section.obs["y"],
        hue="class",
        palette=class_palette,
        data=adata_section.obs,
        s=8,
        legend=False,
    )
    axes[0, 0].set_title("Class")
    axes[0, 0].set_xlabel("X Coordinate")
    axes[0, 0].set_ylabel("Y Coordinate")
    axes[0, 0].tick_params(
        axis="both",
        which="both",
        bottom=False,
        left=False,
        labelbottom=False,
        labelleft=False,
    )
    axes[0, 0].grid(False)  # Remove grid

    # Plot 'subclass' using subclass_color
    sns.scatterplot(
        ax=axes[0, 1],
        x="x",
        y=-adata_section.obs["y"],
        hue="subclass",
        palette=subclass_palette,
        data=adata_section.obs,
        s=8,
        legend=False,
    )
    axes[0, 1].set_title("Subclass")
    axes[0, 1].set_xlabel("X Coordinate")
    axes[0, 1].set_ylabel("Y Coordinate")
    axes[0, 1].tick_params(
        axis="both",
        which="both",
        bottom=False,
        left=False,
        labelbottom=False,
        labelleft=False,
    )
    axes[0, 1].grid(False)  # Remove grid

    # Plot 'supertype' using supertype_color
    sns.scatterplot(
        ax=axes[1, 0],
        x="x",
        y=-adata_section.obs["y"],
        hue="supertype",
        palette=supertype_palette,
        data=adata_section.obs,
        s=8,
        legend=False,
    )
    axes[1, 0].set_title("Supertype")
    axes[1, 0].set_xlabel("X Coordinate")
    axes[1, 0].set_ylabel("Y Coordinate")
    axes[1, 0].tick_params(
        axis="both",
        which="both",
        bottom=False,
        left=False,
        labelbottom=False,
        labelleft=False,
    )
    axes[1, 0].grid(False)  # Remove grid

    # Plot 'cluster' using cluster_color
    sns.scatterplot(
        ax=axes[1, 1],
        x="x",
        y=-adata_section.obs["y"],
        hue="cluster",
        palette=cluster_palette,
        data=adata_section.obs,
        s=8,
        legend=False,
    )
    axes[1, 1].set_title("Cluster")
    axes[1, 1].set_xlabel("X Coordinate")
    axes[1, 1].set_ylabel("Y Coordinate")
    axes[1, 1].tick_params(
        axis="both",
        which="both",
        bottom=False,
        left=False,
        labelbottom=False,
        labelleft=False,
    )
    axes[1, 1].grid(False)  # Remove grid

    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.show()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> Perform PCA and UMAP and cluster with Leiden Algorithm"""
    )
    return


@app.cell
def _(adata_section, sc):
    sc.pp.pca(adata_section)
    sc.pp.neighbors(adata_section)
    sc.tl.umap(adata_section)
    sc.tl.leiden(
        adata_section,
        key_added="clusters",
        resolution=1.0,
        directed=False,
        n_iterations=2,
    )
    return


@app.cell
def _(adata_section, plt, sc):
    plt.rcParams["figure.figsize"] = (8, 8)
    sc.pl.umap(adata_section, color=["clusters"], wspace=0.2)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> Since the spatial coordinates are stored in  `.obsm[X_spatial]` you can plot the section with `sc.pl.spatial`"""
    )
    return


@app.cell
def _(adata_section, sc):
    # Generate the spatial plot
    sc.pl.spatial(
        adata_section,
        color="class",
        color_map="Accent_r",
        spot_size=0.04,
        title="Section 80 colored by Class",
    )
    return


@app.cell
def _(adata_section, sc):
    # Subset the AnnData object to keep only cells belonging to a specific class
    # and plot them again with sc.pl.spatial
    adata_section_one_class = adata_section[
        adata_section.obs["class"] == "01 IT-ET Glut"
    ]
    sc.pl.spatial(
        adata_section_one_class,
        color="class",
        color_map="Accent_r",
        spot_size=0.04,
        title="Section 80 (one Class)",
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ### Plot gene expression in space

    <font size="3">

    Since each spot in the spatial data corresponds to a specific location and its associated gene expression profile, we can visualize spatial gene expression.

    We can do this using the function `sc.pl.spatial`, it requires the name of the variable index to indicate the genes to plot.

    Let's take a look at `adata_section`.var:
    """
    )
    return


@app.cell
def _(adata_section):
    adata_section.var.head()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3">

    Change the index of the `adata_section.var` to `gene_symbol` for clarity
    """
    )
    return


@app.cell
def _(adata_section):
    # Reset the index to turn the current index into a column
    adata_section.var.reset_index(inplace=True)
    adata_section.var.set_index("gene_symbol", inplace=True)
    adata_section.var.head()
    return


@app.cell
def _(adata_section, sc):
    # Define genes to plot
    genes_toplot = ["Zic1", "Penk", "Gfap", "Nr4a2", "Satb2"]

    sc.pl.spatial(adata_section, color=genes_toplot, spot_size=0.04)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""<font size="3"> Plot your favourite gene/s""")
    return


@app.cell
def _():
    # genes_toplot = [.....]

    # sc.pl.spatial(adata_section, color=genes_toplot,spot_size=0.04)
    return


@app.cell
def _(start_time, time):
    _end_time = time.time()
    _elapsed_time = (_end_time - start_time) / 60
    print(f"Execution Time: {_elapsed_time:.2f} minutes")
    return


@app.cell
def _():
    import gc

    # collect garbage
    gc.collect()
    return (gc,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    # Prediction of spatial patterns for unmeasured genes using scRNA-seq data with SpaGE
    [SpaGE: Spatial Gene Enhancement using scRNA-seq (Abdelaal et al. 2020)](https://academic.oup.com/nar/article/48/18/e107/5909530)
    """
    )
    return


@app.cell
def _(time):
    start_time_1 = time.time()
    return (start_time_1,)


@app.cell
def _():
    from SpaGE.main import SpaGE
    import scipy.stats as st
    return (st,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <figure>
        <img src="img/spage.jpg" width="700" height="280" alt="Description of the image">
        <figcaption>From <a href="https://academic.oup.com/nar/article/48/18/e107/5909530" target="_blank">Abdelaal et al. (2020) NAR</a></figcaption>
    </figure>
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3"> SpaGE takes as input the (targeted) spatial dataset (query) and a single-cell RNA dataset used as reference. The two datasets should be generated under the same conditions (same species, tissue, region) as much as possible.

    <font size="3"> We will use [Mouse whole-brain transcriptomic cell type atlas (Hongkui Zeng)](https://www.nature.com/articles/s41586-023-06812-z).This scRNAseq dataset profiled 7 million cells (approximately 4.0 million cells passing quality control). More in detail:

     - <font size="3"> 1.7 million single cell transcriptomes spanning the whole adult mouse brain using 10Xv2 chemistry (WMB-10Xv2)

     - <font size="3"> 2.3 million single cell transcriptomes spanning the whole adult mouse brain using 10Xv3 chemistry (WMB-10Xv3)

     - <font size="3"> 1687 single cell transcriptomes spanning the whole adult mouse brain using the 10X Multiome chemistry (WMB-10XMulti)

    <figure>
        <img src="img/sc.png" width="700" height="280" alt="Description of the image">
        <figcaption>From <a href="https://www.nature.com/articles/s41586-023-06812-z" target="_blank">Yao et al. (2023) Nature Methods</a></figcaption>
    </figure>
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3"> The size is of the combined single-cell object from AbcProjectCache is around 280GB. For this reason, the three objects have been previously downloaded, concatenated, preprocessed and subsetted to obtain NNN cells. For your knowledge, you can find all the steps in `obtain_scref.py`.

    <font size="3"> Let's read the resulting single-cell AnnData object:
    """
    )
    return


@app.cell
def _(ad, data_dir):
    adata_sc = ad.read_h5ad(f"{data_dir}/SpaGE_data/sc_adata_1percent.h5ad")
    return (adata_sc,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""<font size="3"> Inspect the object:""")
    return


@app.cell
def _(adata_sc):
    adata_sc
    return


@app.cell
def _(adata_sc):
    adata_sc.obs.head()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""<font size="3"> Add feature metadata to the AnnData object""")
    return


@app.cell
def _(data_dir, pd):
    genes = pd.read_csv(
        f"{data_dir}/abc_download_root/metadata/WMB-10X/gene.csv", index_col=0
    )

    genes.head()
    return (genes,)


@app.cell
def _(adata_sc, genes):
    adata_sc.var = genes
    return


@app.cell
def _(adata_sc):
    # Reset the index to turn the current index into a column
    adata_sc.var.reset_index(inplace=True)
    adata_sc.var.set_index("gene_symbol", inplace=True)
    adata_sc.var.head()
    return


@app.cell
def _(gc):
    # collect garbage
    gc.collect()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""<font size="3"> Set up inputs for SpaGE:""")
    return


@app.cell
def _(adata_sc, pd):
    # Extract the count data and transform them into a Pandas DataFrame
    RNA_data = pd.DataFrame(adata_sc.X.todense())
    return (RNA_data,)


@app.cell
def _(RNA_data, adata_sc):
    # Add gene names to the RNA_data columns
    RNA_data.columns = adata_sc.var.index
    return


@app.cell
def _(RNA_data, np):
    Genes_count = np.sum(RNA_data > 0, axis=1)
    RNA_data_1 = RNA_data.loc[Genes_count >= 10, :]
    del Genes_count
    return (RNA_data_1,)


@app.cell
def _(RNA_data_1, np):
    def Log_Norm_cpm(x):
        return np.log(x / np.sum(x) * 1000000 + 1)


    RNA_data_2 = RNA_data_1.apply(Log_Norm_cpm, axis=0)
    return Log_Norm_cpm, RNA_data_2


@app.cell
def _(RNA_data_2):
    RNA_data_3 = RNA_data_2.T
    return (RNA_data_3,)


@app.cell
def _(RNA_data_3):
    RNA_data_3.head()
    return


@app.cell
def _(RNA_data_3):
    RNA_data_4 = RNA_data_3.dropna()
    return (RNA_data_4,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <span style="color:; font-size: 15px;"> **How many genes do the spatial and single-cell data set have in common?**

    <span style="color:; font-size: 15px;"> **How many genes are measured in the single-cell dataset that are not measured in the spatial dataset?**
    """
    )
    return


@app.cell
def _(RNA_data_4, adata_sc, adata_section):
    gene_intersection = set(list(adata_section.var.index)).intersection(
        set(list(adata_sc.var.index))
    )
    genes_not_intersection = list(
        set(RNA_data_4.index) - set(adata_section.var.index)
    )
    print(
        f"Number of genes measured both in the sc and spatial datasets: {len(gene_intersection)}"
    )
    print(
        f"Number of genes measured in the sc reference only: {len(genes_not_intersection)}"
    )
    return


@app.cell
def _(adata_section, pd):
    # Extract count matrix from adata_section and rename index and column names

    spatial_data = pd.DataFrame(adata_section.X)
    spatial_data.index = adata_section.obs.index
    spatial_data.columns = adata_section.var.index
    return (spatial_data,)


@app.cell
def _(Log_Norm_cpm, spatial_data):
    spatial_data_1 = spatial_data.apply(Log_Norm_cpm, axis=0)
    return (spatial_data_1,)


@app.cell
def _(spatial_data_1):
    brain_region_specific_genes = [
        "Bcl11b",
        "Cux2",
        "Fezf2",
        "Tbr1",
        "Satb2",
        "Foxp2",
        "Penk",
        "Zic1",
        "Hoxb2",
        "Dlx6",
    ]
    overlap_genes = list(
        set(list(spatial_data_1.columns)) & set(brain_region_specific_genes)
    )
    overlap_genes
    return brain_region_specific_genes, overlap_genes


@app.cell
def _(brain_region_specific_genes, overlap_genes):
    # Checking for genes from brain_region_specific_genes that are NOT measured by spatial data
    non_overlap_genes = list(set(brain_region_specific_genes) - set(overlap_genes))
    return (non_overlap_genes,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Leave-one-gene-out cross validation""")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> Define the function to predict genes measured in the spatial dataset to have a ground truth and plot the measured expression next to the predicted one."""
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ```python
    def predicted_GE_LOOCV(Gene_set, spatial_data, RNA_data):

        # Initialize an empty DataFrame to store the predicted values
        predicted_df = pd.DataFrame(index=spatial_data.index)

        for i in Gene_set:
            # Predict the expression of the current gene using the SpaGE method
            Imp_Genes = SpaGE(spatial_data.drop(i, axis=1), RNA_data.T, n_pv=30, genes_to_predict=[i])
            Imp_Genes.index = spatial_data.index

            # Add the predicted values for the current gene as a new column in the DataFrame
            predicted_df[i] = Imp_Genes[i]

        return predicted_df
    """
    )
    return


@app.cell
def _(data_dir, pd):
    predicted_df = pd.read_csv(
        f"{data_dir}/SpaGE_data/predicted_GE_loocv_SpaGE.csv", index_col=0
    )
    return (predicted_df,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3"> Since we have a ground truth, create a Series to store Spearman correlation results for each gene.

    <font size="3"> Our gene_set in this case is a set of genes shared between the spatial and the sc datasets.
    """
    )
    return


@app.cell
def _(np, plt):
    import matplotlib.gridspec as gridspec  # For precise subplot layout control
    from scipy.stats import spearmanr

    plt.style.use("dark_background")


    def plot_measured_vs_predicted_spatial(
        Gene_set, spatial_data, predicted_df, adata_section
    ):
        """
        Plot measured and predicted spatial expression for genes, with calculated Spearman correlations.

        Parameters:
            Gene_set (list): List of genes to visualize.
            spatial_data (DataFrame): Measured expression data (columns are genes, rows are spots).
            predicted_df (DataFrame): Predicted expression data (columns are genes, rows are spots).
            adata_section (AnnData): Spatial data with 'x' and 'y' coordinates.

        Returns:
            dict: Spearman correlations for each gene.
        """
        correlations = {}  # Dictionary to store Spearman correlations

        for gene in Gene_set:
            # Calculate Spearman correlation
            correlation = spearmanr(spatial_data[gene], predicted_df[gene])[0]
            correlations[gene] = correlation

            # Create a figure with two scatterplots
            fig = plt.figure(figsize=(15, 8))  # Adjust figure size
            gs = gridspec.GridSpec(
                1, 3, width_ratios=[1, 1, 0.05], wspace=0.3
            )  # Create grid spec for layout

            # --- Measured Gene Expression ---
            ax0 = fig.add_subplot(gs[0])
            cmap_measured = spatial_data[gene]
            cmap_measured = np.clip(
                cmap_measured, None, np.percentile(cmap_measured, 99)
            )  # Clip to 99th percentile
            sc1 = ax0.scatter(
                adata_section.obs["x"],
                -adata_section.obs["y"],
                s=1,
                c=cmap_measured,
                cmap="viridis",
                alpha=1,
            )

            ax0.set_title(f"Measured Expression: {gene}", fontsize=12)
            ax0.set_xlabel("X Coordinate")
            ax0.set_ylabel("Y Coordinate")
            ax0.set_aspect("equal", adjustable="box")
            ax0.grid(False)

            # --- Predicted Gene Expression ---
            ax1 = fig.add_subplot(gs[1])
            cmap_predicted = predicted_df[gene]
            cmap_predicted = np.clip(
                cmap_predicted, None, np.percentile(cmap_predicted, 99)
            )  # Clip to 99th percentile
            sc2 = ax1.scatter(
                adata_section.obs["x"],
                -adata_section.obs["y"],
                s=1,
                c=cmap_predicted,
                cmap="viridis",
                alpha=1,
            )

            ax1.set_title(f"Predicted Expression: {gene}", fontsize=12)
            ax1.set_xlabel("X Coordinate")
            ax1.set_ylabel("Y Coordinate")
            ax1.set_aspect("equal", adjustable="box")
            ax1.grid(False)

            # --- Colorbar ---
            cbar_ax = fig.add_subplot(gs[2])  # Third subplot for color bar
            cbar = fig.colorbar(sc1, cax=cbar_ax)
            cbar.set_label("Expression")

            # Adjust layout and show
            plt.tight_layout()
            plt.show()

        return correlations
    return (plot_measured_vs_predicted_spatial,)


@app.cell
def _(
    adata_section,
    overlap_genes,
    plot_measured_vs_predicted_spatial,
    predicted_df,
    spatial_data_1,
):
    correlations = plot_measured_vs_predicted_spatial(
        overlap_genes, spatial_data_1, predicted_df, adata_section
    )
    return (correlations,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> Let's take a look at the Spearman Correlations between measured and predicted gene expression:"""
    )
    return


@app.cell
def _(correlations, pd):
    # Since we have a ground truth, create a Series to store Spearman correlation results for each gene
    # Our gene_set in this case is a set of genes shared between the spatial and the sc datasets
    correlations_spage = pd.DataFrame(
        list(correlations.items()), columns=["Gene", "correlations_spage"]
    ).set_index("Gene")
    return (correlations_spage,)


@app.cell
def _(correlations_spage):
    correlations_spage
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""### Predict unmeasured genes""")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3">  Define a function to predict unmeasured genes in the spatial dataset. 

    <font size="3">  In this case correlations cannot be calculated as there is no ground truth available.
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ```python

    def predicted_unmeasured_GE(Gene_set, spatial_data, RNA_data):

        # Initialize an empty DataFrame to store the predicted values
        predicted_df = pd.DataFrame(index=spatial_data.index)

        for i in Gene_set:
            # Predict the expression of the current gene using the SpaGE method
            Imp_Genes = SpaGE(spatial_data, RNA_data.T, n_pv=30, genes_to_predict=[i])
            Imp_Genes.index = spatial_data.index

            # Add the predicted values for the current gene as a new column in the DataFrame
            predicted_df[i] = Imp_Genes[i]

        return predicted_df
    """
    )
    return


@app.cell
def _(data_dir, pd):
    predicted_df_1 = pd.read_csv(
        f"{data_dir}/SpaGE_data/predicted_unmeasured_GE_SpaGE.csv", index_col=0
    )
    return (predicted_df_1,)


@app.cell
def _(np, plt):
    def plot_predicted_spatial(Gene_set, predicted_df, adata_section):
        """
        Plot predicted spatial expression for genes.

        Parameters:
            Gene_set (list): List of genes to visualize.
            predicted_df (DataFrame): Predicted expression data (columns are genes, rows are spots).
            adata_section (AnnData): Spatial data with 'x' and 'y' coordinates.

        Returns:
            None
        """
        for gene in Gene_set:
            # Create a figure for the predicted expression
            fig, ax = plt.subplots(figsize=(8, 6))  # Adjust figure size

            # Get predicted values and clip to the 99th percentile
            cmap_predicted = predicted_df[gene]
            cmap_predicted = np.clip(
                cmap_predicted, None, np.percentile(cmap_predicted, 99)
            )

            # Plot the predicted expression
            scatter = ax.scatter(
                adata_section.obs["x"],
                -adata_section.obs["y"],
                s=1,
                c=cmap_predicted,
                cmap="viridis",
                alpha=1,
            )

            # Add title and labels
            ax.set_title(f"Predicted Expression: {gene}", fontsize=14)
            ax.set_xlabel("X Coordinate")
            ax.set_ylabel("Y Coordinate")
            ax.set_aspect("equal", adjustable="box")
            ax.grid(False)

            # Add a colorbar
            cbar = plt.colorbar(scatter, ax=ax, pad=0.01)
            cbar.set_label("Expression")

            # Adjust layout and show
            plt.tight_layout()
            plt.show()
    return (plot_predicted_spatial,)


@app.cell
def _(
    adata_section,
    non_overlap_genes,
    plot_predicted_spatial,
    predicted_df_1,
):
    plot_predicted_spatial(non_overlap_genes, predicted_df_1, adata_section)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3"> There is no definitive ground truth for the real gene expression profiles of these genes. However, an alternative approach could be to plot region-specific genes and verify whether their expression aligns with the expected brain regions.

    <font size="3"> For example, Tbr1 is known to be Isocortex-specific; does its expression show higher levels in the Isocortex? Similarly, Foxp2 is Striatum-specific; does it exhibit a Striatum-specific expression pattern?

    <font size="3"> Use [this](https://mouse.brain-map.org/search/index) resource to check region-specific gene expression.
    """
    )
    return


@app.cell
def _(start_time_1, time):
    _end_time = time.time()
    _elapsed_time = (_end_time - start_time_1) / 60
    print(f"Execution Time SpaGE: {_elapsed_time:.2f} minutes")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> Let's delete some objects we won't be using anymore to free some RAM:"""
    )
    return


@app.cell
def _(RNA_data_4, spatial_data_1):
    del RNA_data_4, spatial_data_1
    return


@app.cell
def _(gc):
    # collect garbage
    gc.collect()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    # Unmeasured gene imputation with Tangram
    [Deep learning and alignment of spatially resolved single-cell transcriptomes with Tangram (Biancalani et al. 2021)](https://www.nature.com/articles/s41592-021-01264-7)
    """
    )
    return


@app.cell
def _(time):
    start_time_2 = time.time()
    return (start_time_2,)


@app.cell
def _(sc):
    import tangram as tg

    from sklearn.preprocessing import MinMaxScaler

    sc.settings.verbosity = 3
    sc.settings.set_figure_params(dpi=80, facecolor="white")
    return (tg,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    #### Common gene set between reference and spatial dataset

    <font size="3"> We want to select our training genes. These genes are shared between the two datasets and should capture the biological variance between cell types. For this, we first compute marker genes on the single-cell data and then use Tangram’s preprocessing function to subset to those genes that are also present in the spatial data.
    """
    )
    return


@app.cell
def _(adata_sc, adata_section):
    markers = list(
        set.intersection(set(adata_sc.var_names), set(adata_section.var_names))
    )
    len(markers)
    return (markers,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> `tg.pp_adatas` computes the overlap between single-cell data and spatial data on the list of genes provided in the genes argument, it then stores the resulting gene set under 'training_genes' in both adata objects under the `.uns` key and enforces consistent ordering of the genes."""
    )
    return


@app.cell
def _(adata_sc, adata_section, markers, tg):
    tg.pp_adatas(
        adata_sc, adata_section, genes=markers
    )  # using the same single-cell reference that we used to run SpaGE
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""<font size="3"> Check that the function performs as we expect:""")
    return


@app.cell
def _(adata_sc, adata_section):
    assert "training_genes" in adata_sc.uns
    assert "training_genes" in adata_section.uns

    print(f"Number of training_genes: {len(adata_sc.uns['training_genes'])}")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    #### Computing the map from single-cells to spatial voxels

    <font size="3"> Having specified the training genes, we can now create the map from dissociated single-cell measurements to the spatial locations. For this, we are going to use the `map_cells_to_space` function from tangram. This function has two different modes, `mode='cells'` and `mode='clusters'`. The latter only maps averaged single-cells which makes the mapping computationally faster and more robust when mapping between specimen.
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ```python
    ad_map = tg.map_cells_to_space(
        adata_sc,
        adata_section,
        mode="cells",
        density_prior="rna_count_based",
        num_epochs=500,
        device="cpu",  # or: cpu
    )
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> We run `tg.map_cells_to_space` for you (takes a while to run), let's just read the resulting AnnData object"""
    )
    return


@app.cell
def _(ad, data_dir):
    ad_map = ad.read_h5ad(f"{data_dir}/Tangram_data/ad_map_tangram.h5ad")
    ad_map
    return (ad_map,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3"> We observe that Tangram’s mapping from cell i to spatial voxels j is stored in the .X property of ad_map.
    <font size="3">  The meaning of the .var and .obs also changes:

    - <font size="3"> in `.var` we have the available metadata of the spatial data, adata_section
    - <font size="3"> in `.obs` we have the available metadata of the single-cell data, adata_sc
    - <font size="3"> In addition, the information about the training run is stored in the .uns key, see `.uns['training_genes_df']` and `.uns[training_history]`.
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> Now we can **project the genes present in the single-cell data to the spatial locations**. This is easily achieved by multiplying the mapping matrix stored in ad_map with the original single-cell data stored in adata_sc. Tangram already provides a convenience function which takes in a mapping and the corresponding single-cell data. The result is a **spatial voxel by genes matrix** which technically is identical to the original spatial data adata_section but **contains expression values for all genes**."""
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ```python
    ad_ge = tg.project_genes(adata_map=ad_map, adata_sc=adata_sc)
    ad_ge
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> We run `tg.project_genes` for you, let's just read the resulting AnnData object"""
    )
    return


@app.cell
def _(ad, data_dir, np):
    ad_ge = ad.read_h5ad(f"{data_dir}/Tangram_data/ad_ge.h5ad")

    ## add .obsm['X_spatial'] so we can use sc.pl.spatial to plot gene expression
    ad_ge.obsm["X_spatial"] = np.array(ad_ge.obs[["x", "y"]])
    ad_ge
    return (ad_ge,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3"> Next, we will compare the new spatial data with the original measurements.

    <font size="3"> To do this we will plot the true expression and the predicted expression of the shared genes, as well as the Spearman correlation between the true and predicted expression in all the spots.
    """
    )
    return


@app.cell
def _(overlap_genes):
    overlap_genes_1 = [gene.lower() for gene in overlap_genes]
    overlap_genes_1
    return (overlap_genes_1,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""<font size="3"> Plot the true expression from adata_section""")
    return


@app.cell
def _(adata_section, overlap_genes_1, sc):
    sc.pl.spatial(adata_section, color=overlap_genes_1, spot_size=0.04)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""<font size="3"> Plot the predicted expression from ad_ge""")
    return


@app.cell
def _(ad_ge):
    ad_ge.var.reset_index(inplace=True)
    ad_ge.var.set_index("_index", inplace=True)
    return


@app.cell
def _(ad_ge, overlap_genes_1, sc):
    sc.pl.spatial(ad_ge, color=overlap_genes_1, spot_size=0.04)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""<font size="3"> Calculate Spearman correlations""")
    return


@app.cell
def _(ad_ge, adata_section, overlap_genes_1, pd, st):
    ad_true = adata_section[:, adata_section.var_names.isin(overlap_genes_1)]
    ad_ge_predicted = ad_ge[:, ad_ge.var_names.isin(overlap_genes_1)]
    correlation_dict = {}
    for gene in overlap_genes_1:
        expr1 = ad_true[:, gene].X.flatten()
        expr2 = ad_ge_predicted[:, gene].X.flatten()
        corr, _ = st.spearmanr(expr1, expr2)
        correlation_dict[gene] = corr
    tangram_correlations = pd.DataFrame.from_dict(
        correlation_dict, orient="index", columns=["correlations_tangram"]
    )
    tangram_correlations.index = tangram_correlations.index.str.capitalize()
    tangram_correlations
    return ad_ge_predicted, ad_true, tangram_correlations


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> Since we predicted the same genes as SpaGE, let's compare the Spearman correlations:"""
    )
    return


@app.cell
def _(correlations_spage, pd, tangram_correlations):
    all_correlations = pd.concat(
        [correlations_spage, tangram_correlations], axis=1
    )
    all_correlations[["correlations_spage", "correlations_tangram"]]
    return (all_correlations,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> **Which tool results in higher correlation between the true-measured gene expression and the predicted expression of the genes of interest?**"""
    )
    return


@app.cell
def _(start_time_2, time):
    _end_time = time.time()
    _elapsed_time = (_end_time - start_time_2) / 60
    print(f"Execution Time Tangram: {_elapsed_time:.2f} minutes")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> Let's delete some objects we won't be using anymore to free some RAM:"""
    )
    return


@app.cell
def _(ad_ge, ad_map):
    del ad_map, ad_ge
    return


@app.cell
def _(
    ad_ge_predicted,
    ad_true,
    all_correlations,
    correlations_spage,
    predicted_df_1,
    tangram_correlations,
):
    del (
        all_correlations,
        correlations_spage,
        tangram_correlations,
        predicted_df_1,
        ad_true,
        ad_ge_predicted,
    )
    return


@app.cell
def _(gc):
    gc.collect()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    # Cell type deconvolution with cell2location
    [Cell2location maps fine-grained cell types in spatial transcriptomics (Kleshchevnikov et al. 2022)](https://www.nature.com/articles/s41587-021-01139-4)
    """
    )
    return


@app.cell
def _(time):
    start_time_3 = time.time()
    return (start_time_3,)


@app.cell
def _(sc):
    # import squidpy as sq
    import cell2location as c2l

    sc.settings.verbosity = 3
    sc.settings.set_figure_params(dpi=80, facecolor="white")
    return (c2l,)


@app.cell
def _(adata_sc):
    # set raw layer as X
    adata_sc.layers["raw"] = adata_sc.X
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> Add metadata with cell type annotation to the single-cell AnnData object"""
    )
    return


@app.cell
def _(adata_sc, data_dir, pd):
    # read csv
    metadata = pd.read_csv(
        f"{data_dir}/abc_download_root/metadata/WMB-10X/views/cell_metadata_with_cluster_annotation.csv",
        index_col=0,
    )
    # filter metadata to keep only obervations in the subsetted SC AnnData object
    metadata = metadata.loc[metadata.index.intersection(adata_sc.obs.index)]
    # reindex rows
    metadata = metadata.reindex(adata_sc.obs.index)
    # assign metadata to adata_sc.obs (in this way metadata replaces all fields previously in obs)
    adata_sc.obs = metadata

    adata_sc.obs.head()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> Identify the shared set of genes between spatial and single-cell"""
    )
    return


@app.cell
def _(adata_sc, adata_section):
    shared_features = [
        feature
        for feature in adata_section.var_names
        if feature in adata_sc.var_names
    ]
    adata_sc_1 = adata_sc[:, adata_sc.var.index.isin(shared_features)].copy()
    adata_section_1 = adata_section[:, shared_features].copy()
    adata_sc_1 = adata_sc_1[:, shared_features].copy()
    adata_section_1.shape[1] == adata_sc_1.shape[1]
    print(
        f"Number of shared genes between spatial data and reference sc: {adata_section_1.shape[1]}"
    )
    return adata_sc_1, adata_section_1


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3"> **Fit the reference model**

    <font size="3"> When your spatial transcriptomics dataset is whole-transcriptome: The default parameters cell_count_cutoff=5, cell_percentage_cutoff2=0.03, nonz_mean_cutoff=1.12 are a good starting point, however, you can increase the cut-off to exclude more genes. To preserve marker genes of rare cell types we recommend low cell_count_cutoff=5, however, cell_percentage_cutoff2 and nonz_mean_cutoff can be increased to select between 8k-16k genes.

    <font size="3"> In this 2D histogram, orange rectangle highlights genes excluded based on the combination of number of cells expressing that gene (Y-axis) and average RNA count for cells where the gene was detected (X-axis).

    <font size="3"> This step can be skipped when a limited gene panel is available.
    """
    )
    return


@app.cell
def _(adata_sc_1, adata_section_1, c2l):
    selected = c2l.utils.filtering.filter_genes(
        adata_sc_1,
        cell_count_cutoff=5,
        cell_percentage_cutoff2=0.03,
        nonz_mean_cutoff=1.12,
    )
    adata_sc_2 = adata_sc_1[:, selected].copy()
    adata_section_2 = adata_section_1[:, selected].copy()
    return adata_sc_2, adata_section_2


@app.cell
def _(adata_section_2):
    print(
        f"The spatial AnnData object has {adata_section_2.shape[0]} obs and {adata_section_2.shape[1]} features."
    )
    return


@app.cell
def _(adata_sc_2):
    print(
        f"The single-cell AnnData object has {adata_sc_2.shape[0]} obs and {adata_sc_2.shape[1]} features."
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3"> **Estimation of reference cell type signatures (NB regression)**

    <font size="3"> The following two command are computationally intensive and require GPU. We run them for you. You can read the output from `stdata_deconv.h5ad`
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    <font size="3"> The signatures are estimated from scRNA-seq data, accounting for batch effect, using a Negative binomial regression model.

    <font size="3"> First, prepare anndata object for the regression model:

    ```python
    c2l.models.RegressionModel.setup_anndata(
        adata=adata_sc,
        #batch_key="Replicates", # there's no batch 
        labels_key="class", # cell type = class
        #categorical_covariate_keys=["assay"],
        layer="raw",
    )
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ```python
    model = c2l.models.RegressionModel(adata_sc)
    # default, try on GPU:
    model.train(max_epochs=250, batch_size=2500, train_size=1, lr=0.002)

    model.export_posterior(
        adata_sc,
        sample_kwargs={"num_samples": 1000, "batch_size": 2500},
    )
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> **Train the model** to estimate the reference cell type signatures:"""
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ```python
    # export estimated expression in each cluster
    if "means_per_cluster_mu_fg" in adata_sc.varm.keys():
        inf_aver = adata_sc.varm["means_per_cluster_mu_fg"][
            [f"means_per_cluster_mu_fg_{i}" for i in adata_sc.uns["mod"]["factor_names"]]
        ].copy()
    else:
        inf_aver = adata_sc.var[
            [f"means_per_cluster_mu_fg_{i}" for i in adata_sc.uns["mod"]["factor_names"]]
        ].copy()

    inf_aver.columns = adata_sc.uns["mod"]["factor_names"]
    inf_aver.head()

    # cell 2 location cell type mapping
    print('start with Cell2location')
    c2l.models.Cell2location.setup_anndata(
        adata=adata_section,
    )

    model = c2l.models.Cell2location(
        adata_section,
        cell_state_df=inf_aver,
        N_cells_per_location=8,
    )
    model.view_anndata_setup()

    print('start with training')
    model.train(max_epochs=30000, batch_size=None, train_size=1)#, use_gpu=use_gpu)

    adata_section = model.export_posterior(
        adata_section,
        sample_kwargs={
            "num_samples": 1000,
            "batch_size": model.adata.n_obs}#,
            #"use_gpu": use_gpu,
    )


    adata_section.obs[adata_section.uns["mod"]["factor_names"]] = adata_section.obsm["q05_cell_abundance_w_sf"]
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""<font size="3"> Read the pre-computed AnnData object with cell2location results"""
    )
    return


@app.cell
def _(ad, data_dir):
    adata_section_3 = ad.read_h5ad(
        f"{data_dir}/cell2location_data/stdata_deconv.h5ad"
    )
    return (adata_section_3,)


@app.cell
def _(adata_section_3):
    adata_section_3.obs[adata_section_3.obs["class"].unique()]
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""<font size="3"> Visualize cell abundance in spatial coordinates:""")
    return


@app.cell
def _(adata_section_3, sc):
    sc.pl.spatial(
        adata_section_3,
        color=["01 IT-ET Glut", "04 DG-IMN Glut", "30 Astro-Epen"],
        spot_size=0.04,
    )
    return


@app.cell
def _(start_time_3, time):
    _end_time = time.time()
    _elapsed_time = (_end_time - start_time_3) / 60
    print(f"Execution Time cell2location: {_elapsed_time:.2f} minutes")
    return


@app.cell
def _(gc):
    # collect garbage
    gc.collect()
    return


@app.cell
def _():
    import marimo as mo
    return (mo,)


if __name__ == "__main__":
    app.run()
